### ISSUE TITLE
🎨 Redesign Player list view

### ISSUE THREAD

**Issue by petrspelos** [control-net/libre-cards-against-humanity#26]
## Summary

It's time to redesign and polish our Player list view component. 🎉 

![image](https://user-images.githubusercontent.com/21304428/136702906-7c476bd2-11c0-4dde-b5af-352fefd1369b.png)

## What is needed

This is mostly HTML / CSS work.

If you're a designer, but aren't able to code, feel free to send your design in the comments below and I'm sure someone will be able to bring your design into life. ☺️ 

The HTML ([razor file](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-5.0)) in question is [PlayersView](https://github.com/control-net/libre-cards-against-humanity/blob/main/src/LibreCards.BlazorApp/Components/PlayersView.razor).

The CSS resource is our [app.css](https://github.com/control-net/libre-cards-against-humanity/blob/main/src/LibreCards.BlazorApp/wwwroot/css/app.css)

## Want to work on this? ☺

❤️  First of all, thank you so much for considering tackling this issues.

🤝 Feel free to discuss the implementation in the comments and/or ask for any clarifications!

💬 Let us know you'd like to work on this issue by commenting underneath so that we don't work on the same thing

**Comment by petrspelos** [comment]
Alrighty, if you have any question, feel free to ask here. ☺️

**Comment by vinmaster** [comment]
Let me know what you think: https://github.com/control-net/libre-cards-against-humanity/pull/36
