### ISSUE TITLE
🎨 Redesign Card Drawer

### ISSUE THREAD

**Issue by petrspelos** [control-net/libre-cards-against-humanity#27]
## Summary

Our Card Drawer is in a dire need of a redesign. 😅 

![image](https://user-images.githubusercontent.com/21304428/136703086-cae18928-410e-4ed2-95cd-4f242691deaf.png)

## How to implement

This is mostly an HTML / CSS task, but might require a tiny bit of Blazor, depending on the severity of the redesign.

Currently, the cards contain simple checkboxes (related to #23 ), which could be redesigned using some CSS magic.

Ideally, we'd click on the cards themself instead of the checkbox and have them change the way they look, maybe they move up...

The Submit button should also probably look a little more presentable. 😅 

Be creative, this is not a concrete task. ☺️ 

## Relevant files

- [Card Drawer Component](https://github.com/control-net/libre-cards-against-humanity/blob/main/src/LibreCards.BlazorApp/Components/CardDrawer.razor)
- [app.css](https://github.com/control-net/libre-cards-against-humanity/blob/main/src/LibreCards.BlazorApp/wwwroot/css/app.css)

## Want to work on this? ☺

❤️  First of all, thank you so much for considering tackling this issues.

🤝 Feel free to discuss the implementation in the comments and/or ask for any clarifications!

💬 Let us know you'd like to work on this issue by commenting underneath so that we don't work on the same thing

**Comment by vinmaster** [comment]
Hi, I've created a PR for this. Let me know what you think. Thanks
